<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutDir>..\..\bin\$(Configuration)\Components</OutDir>
    <TargetFramework>net4.6.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>

    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\LiveSplit.Core\LiveSplit.Core.csproj" />
    <ProjectReference Include="..\..\UpdateManager\UpdateManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DarkUI" Version="2.0.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2420.47" />
    <PackageReference Include="Ookii.Dialogs.WinForms" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

</Project>
